// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200609092616_API contendo tabela Users e Manager")]
    partial class APIcontendotabelaUserseManager
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Api.Domain.Entities.ManagerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateAt");

                    b.Property<string>("Crm_IPV4")
                        .HasMaxLength(100);

                    b.Property<int>("Crm_LICENSES")
                        .HasMaxLength(3);

                    b.Property<int>("Crm_PORT")
                        .HasMaxLength(100);

                    b.Property<bool>("Crm_START");

                    b.Property<string>("Crm_TAG")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Faturamento_IPV4")
                        .HasMaxLength(100);

                    b.Property<int>("Faturamento_LICENSES")
                        .HasMaxLength(3);

                    b.Property<int>("Faturamento_PORT")
                        .HasMaxLength(100);

                    b.Property<bool>("Faturamento_START");

                    b.Property<string>("Faturamento_TAG")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Site_IPV4")
                        .HasMaxLength(100);

                    b.Property<int>("Site_LICENSES")
                        .HasMaxLength(3);

                    b.Property<int>("Site_PORT")
                        .HasMaxLength(10);

                    b.Property<bool>("Site_START");

                    b.Property<string>("Site_TAG")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdateAt");

                    b.Property<string>("Vendas_IPV4")
                        .HasMaxLength(100);

                    b.Property<int>("Vendas_LICENSES")
                        .HasMaxLength(3);

                    b.Property<int>("Vendas_PORT")
                        .HasMaxLength(100);

                    b.Property<bool>("Vendas_START");

                    b.Property<string>("Vendas_TAG")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Crm_IPV4");

                    b.HasIndex("Crm_LICENSES");

                    b.HasIndex("Crm_PORT");

                    b.HasIndex("Crm_START");

                    b.HasIndex("Crm_TAG");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Faturamento_IPV4");

                    b.HasIndex("Faturamento_LICENSES");

                    b.HasIndex("Faturamento_PORT");

                    b.HasIndex("Faturamento_START");

                    b.HasIndex("Faturamento_TAG");

                    b.HasIndex("Site_IPV4");

                    b.HasIndex("Site_LICENSES");

                    b.HasIndex("Site_PORT");

                    b.HasIndex("Site_START");

                    b.HasIndex("Site_TAG");

                    b.HasIndex("Vendas_IPV4");

                    b.HasIndex("Vendas_LICENSES");

                    b.HasIndex("Vendas_PORT");

                    b.HasIndex("Vendas_START");

                    b.HasIndex("Vendas_TAG");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateAt");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<DateTime?>("UpdateAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
