# APENINOS SOFTWARE
version: "2"
services:
  db:
    image: apeninos/asasaas_postgres:version9
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  odoo11:
    image: apeninos/asasaas_odoo:version11.0
    depends_on:
      - db
    ports:
      - "15303:8069"
    tty: true
    command: -- --dev=reload
    #    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./o_addons:/mnt/extra-addons
      - ./o_etc:/etc/odoo
volumes:
  db:
  odoo11:
